name: 🌱 Deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: .markata.cache
          key: ${{ runner.os }}-${{ hashfiles('markata.toml') }}-${{ steps.date.outputs.date }}-markata
          restore-keys: |
            ${{ runner.os }}-${{ hashfiles('markata.toml') }}-markata

      - uses: actions/cache@v3.0.2
        id: node-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install markata
        run: pip install -r requirements.txt

      - name: run markata
        run: markata build --no-pretty

      - name: create root
        run: |
            cp static/index.html markout/index.html

      - name: sw-version
        run: export checksum=$(checksumdir markout ) && cat static/sw.js | envsubst > markout/sw.js

      - name: GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: markout
          build_dir: markout
          jekyll: false
